name: Build Project

on: [pull_request]
  workflow_run:
    workflows: ["Checkout Code", "Install Dependencies"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Build project
      run: make