name: Install Dependencies

on: [pull_request]
  workflow_run:
    workflows: ["Checkout Code"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Install dependencies
      run: choco install mingw make -y
