name: CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: choco install mingw make -y

    - name: Build project
      run: make

    - name: Run functional tests
      run: make run_functional

    - name: Run unit tests
      run: make run_unit

    - name: Clean files
      run: make clean
