name: Functional Tests

on: [pull_request]
  workflow_run:
    workflows: ["Checkout Code", "Install Dependencies", "Build Project"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Run tests
      run: make run_functional
